# Generated by Django 3.1.14 on 2022-02-14 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nonovium_video_backend.video_encoder.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('size', models.PositiveIntegerField(editable=False, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', nonovium_video_backend.video_encoder.fields.VideoField(height_field='height', upload_to='', width_field='width')),
            ],
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('DLT', 'Deleted')], default='P', max_length=3)),
                ('privacy_status', models.CharField(choices=[('PUB', 'Public'), ('PRV', 'Private'), ('WLK', 'With Link')], default='PUB', max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('post_id', models.CharField(default='7d4e3710-848d-41b1-bc44-2a176a1c1d1c', editable=False, max_length=256)),
                ('slug', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to='videos.video')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
