# Generated by Django 3.1.13 on 2021-10-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nonovium_video_backend.video_encoder.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_video", models.FileField(blank=True, upload_to="videos/")),
                ("width", models.PositiveIntegerField(editable=False, null=True)),
                ("height", models.PositiveIntegerField(editable=False, null=True)),
                ("duration", models.FloatField(editable=False, null=True)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "file",
                    nonovium_video_backend.video_encoder.fields.VideoField(
                        height_field="height", upload_to="", width_field="width"
                    ),
                ),
                ("is_video_360", models.BooleanField(default=True)),
                (
                    "video_360",
                    nonovium_video_backend.video_encoder.fields.VideoField(
                        height_field="height", upload_to="", width_field="width"
                    ),
                ),
                ("is_video_sd", models.BooleanField(default=True)),
                (
                    "video_sd",
                    nonovium_video_backend.video_encoder.fields.VideoField(
                        height_field="height", upload_to="", width_field="width"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("short_description", models.TextField(blank=True)),
                ("uploaded_video", models.FileField(blank=True, upload_to="videos/")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
