# Generated by Django 3.1.14 on 2022-02-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='8f4f03e6-063e-4ccb-a10b-57eddba919c7', editable=False, max_length=256),
        ),
    ]
