# Generated by Django 3.1.13 on 2021-10-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="is_video_360",
        ),
        migrations.RemoveField(
            model_name="video",
            name="is_video_sd",
        ),
        migrations.RemoveField(
            model_name="video",
            name="uploaded_video",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_360",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_sd",
        ),
    ]
