# Generated by Django 3.1.13 on 2022-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='938fd5ae-8381-4285-8776-c75041d435ef', editable=False, max_length=256),
        ),
    ]
