# Generated by Django 3.1.13 on 2021-10-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-timestamp"]},
        ),
    ]
