# Generated by Django 3.1.13 on 2022-01-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220104_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='346ef69a-b6c6-4622-ad17-fc6f9e3c3cdc', editable=False, max_length=256),
        ),
    ]
