# Generated by Django 3.1.13 on 2021-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True),
        ),
    ]
