# Generated by Django 3.1.13 on 2022-01-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20220104_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='5b1d7570-5178-49e3-bbae-305a2e7310c6', editable=False, max_length=256),
        ),
    ]
