# Generated by Django 3.1.13 on 2021-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20211028_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.CharField(blank=True, default='djangodbmodelsfieldscharfield', max_length=255, unique=True),
        ),
    ]
