# Generated by Django 3.1.13 on 2021-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
