# Generated by Django 3.1.13 on 2022-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20220104_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='aa4e6d70-e0ef-4d3f-86e4-734f88bd729d', editable=False, max_length=256),
        ),
    ]
