# Generated by Django 3.1.13 on 2021-10-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_short_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="file",
            new_name="file_direct",
        ),
    ]
