# Generated by Django 3.1.13 on 2021-10-28 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videopost_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
