# Generated by Django 3.1.13 on 2021-10-18 15:35

from django.db import migrations, models
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_auto_20211018_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="file",
            field=video_encoding.fields.VideoField(
                default="test", height_field="height", upload_to="", width_field="width"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="height",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="width",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
