# Generated by Django 3.1.13 on 2022-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20220104_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='f827becc-cf39-4245-8759-18cab53997a7', editable=False, max_length=256),
        ),
    ]
