# Generated by Django 3.1.13 on 2021-10-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20211028_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='uuid',
        ),
        migrations.AddField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='<function uuid4 at 0x7f48e2b9bb80>', editable=False, max_length=36),
        ),
    ]
