# Generated by Django 3.1.13 on 2021-10-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_auto_20211018_1635"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={},
        ),
    ]
