# Generated by Django 3.1.13 on 2021-10-18 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0007_auto_20211018_1715"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file_direct",
        ),
        migrations.RemoveField(
            model_name="video",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="video",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.RemoveField(
            model_name="video",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="video",
            name="user",
        ),
        migrations.CreateModel(
            name="VideoPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("short_description", models.TextField(blank=True)),
                ("uploaded_video", models.FileField(blank=True, upload_to="videos/")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_posts",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
