# Generated by Django 3.1.13 on 2021-10-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20211028_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='<function uuid4 at 0x7f632f5c5b80>', editable=False, max_length=36),
        ),
    ]
