# Generated by Django 3.1.13 on 2021-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_auto_20211018_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
