# Generated by Django 3.1.13 on 2021-10-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20211028_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='a5d3b6ff-b138-4a56-bfaa-59fa9a6ccadf', editable=False, max_length=36),
        ),
    ]
