# Generated by Django 3.1.13 on 2022-01-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20220104_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='3f0819ca-d4c5-485a-a2be-dac3b630c643', editable=False, max_length=256),
        ),
    ]
