# Generated by Django 3.1.13 on 2021-10-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20211028_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$cb597986-fcac-4665-b0e1-d4e534e6c50e', editable=False, max_length=36),
        ),
    ]
