# Generated by Django 3.1.13 on 2021-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="uploaded_video",
            field=models.FileField(blank=True, upload_to="videos/"),
        ),
    ]
