# Generated by Django 3.1.14 on 2022-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20220104_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='66840677-b2a4-4f0b-ba00-cab2139dbe9d', editable=False, max_length=256),
        ),
    ]
