# Generated by Django 3.1.13 on 2021-10-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20211028_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$7d667398-f62d-4a9f-b889-15b4df7451a3', editable=False, max_length=36),
        ),
    ]
