# Generated by Django 3.1.14 on 2022-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20220123_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='450c90e7-771a-4cff-8eb4-29aa1dbb272d', editable=False, max_length=256),
        ),
    ]
