# Generated by Django 3.1.14 on 2022-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20220123_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='99ec8213-43ee-4728-a9d1-b4a651acfcd1', editable=False, max_length=256),
        ),
    ]
