# Generated by Django 3.1.13 on 2021-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_auto_20211018_1952"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
