# Generated by Django 3.1.13 on 2021-10-21 00:57

from django.db import migrations
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0012_video_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_360",
            field=video_encoding.fields.VideoField(
                blank=True, editable=False, null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="video_sd",
            field=video_encoding.fields.VideoField(
                blank=True, editable=False, null=True, upload_to=""
            ),
        ),
    ]
