# Generated by Django 3.1.13 on 2021-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20211028_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='privacy_status',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRV', 'Private'), ('WLK', 'With Link')], default='PUB', max_length=3),
        ),
        migrations.AddField(
            model_name='videopost',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('DLT', 'Deleted')], default='P', max_length=3),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$9b984263-6f88-44b3-b76c-707ca3c0779c', editable=False, max_length=256),
        ),
    ]
