# Generated by Django 3.1.14 on 2022-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20220123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='d35471ce-7a89-4886-9099-27390167ee35', editable=False, max_length=256),
        ),
    ]
