# Generated by Django 3.1.13 on 2021-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20211028_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='uploaded_video',
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$a854d558-e067-43d7-9806-5932b738caf4', editable=False, max_length=256),
        ),
    ]
