# Generated by Django 3.1.14 on 2022-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20220123_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='431a9c9a-1ef9-46e3-8df7-6bc6cce02fb9', editable=False, max_length=256),
        ),
    ]
