# Generated by Django 3.1.13 on 2021-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20211110_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$300cd498-bdb3-4682-99bb-f28d3a5a4fbc', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.CharField(blank=True, default='djangodbmodelsfieldscharfield', editable=False, max_length=255, unique=True),
        ),
    ]
