# Generated by Django 3.1.13 on 2021-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20211118_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='$25e8a52c-e76d-4f7c-a999-6e7ae7ab6cdd', editable=False, max_length=256),
        ),
    ]
