# Generated by Django 3.1.14 on 2022-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_auto_20220124_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='5066d0c0-ca0a-4b83-a06e-0e9f80fcfb46', editable=False, max_length=256),
        ),
    ]
