# Generated by Django 3.1.13 on 2021-12-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('videos', '0018_auto_20211130_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='97311a30-a307-4690-8670-7703b7c964a2', editable=False, max_length=256),
        ),
    ]
