# Generated by Django 3.1.13 on 2021-12-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('videos', '0019_auto_20211208_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='3b9bee2d-a1b6-4de4-b81e-755431d8fbc9', editable=False, max_length=256),
        ),
    ]
