# Generated by Django 3.1.13 on 2021-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20211208_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='154b9818-3631-4b81-bef2-9af4331f419e', editable=False, max_length=256),
        ),
    ]
