# Generated by Django 3.1.13 on 2021-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('videos', '0022_auto_20211208_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='44bca7d3-1e81-4b86-a7b6-a80becf01692', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
