# Generated by Django 3.1.13 on 2021-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('videos', '0023_auto_20211208_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='e0c859a5-4fea-48ca-9084-c1450dbb8481', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
    ]
