# Generated by Django 3.1.13 on 2021-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_auto_20211208_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='1caeb422-1220-4646-a1c6-cf178d150cd3', editable=False, max_length=256),
        ),
    ]
