# Generated by Django 3.1.13 on 2021-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_auto_20211208_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='7eba8d7c-4113-438e-a517-faacb92aa05d', editable=False, max_length=256),
        ),
    ]
