# Generated by Django 3.1.13 on 2021-12-08 17:29

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_auto_20211208_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videopost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='462b5ee9-3902-4bea-beff-78344267dc18', editable=False, max_length=256),
        ),
    ]
