# Generated by Django 3.1.13 on 2021-12-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_auto_20211208_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='7268e27e-720b-483c-8366-bbcde6bc3578', editable=False, max_length=256),
        ),
    ]
