# Generated by Django 3.1.13 on 2021-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_auto_20211208_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='fa9043dc-99f1-4efa-bd18-fbd55bcf165a', editable=False, max_length=256),
        ),
    ]
