# Generated by Django 3.1.13 on 2021-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_auto_20211208_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='db6e927e-707a-4ae1-82e2-c1c4fabec6b8', editable=False, max_length=256),
        ),
    ]
