# Generated by Django 3.1.13 on 2021-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0030_auto_20211208_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='54a52e2f-2a25-46ae-a656-0f96bb21983e', editable=False, max_length=256),
        ),
    ]
