# Generated by Django 3.1.13 on 2021-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_auto_20211208_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='fd7c3519-1bf8-4e49-bdea-b606e313bb97', editable=False, max_length=256),
        ),
    ]
