# Generated by Django 3.1.13 on 2021-12-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_auto_20211208_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='sites',
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='3746590b-b2e8-46bc-8a16-2cea5cda6f06', editable=False, max_length=256),
        ),
    ]
