# Generated by Django 3.1.13 on 2021-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_auto_20211208_2030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videopost',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='sites',
        ),
        migrations.AlterField(
            model_name='videopost',
            name='post_id',
            field=models.CharField(default='9f662883-de45-425a-85c0-5533ea5a05e6', editable=False, max_length=256),
        ),
    ]
