# Generated by Django 3.1.14 on 2022-02-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(default='https://avatars.dicebear.com/api/avataaars/55888.svg?size=150', max_length=250, verbose_name='Profile Image URL'),
        ),
    ]
