# Generated by Django 3.1.13 on 2021-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20211015_2010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="This user has not added a bio yet",
                max_length=500,
                verbose_name="Short Bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(default=False, verbose_name="Dark Mode"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.CharField(
                default="https://avatars.dicebear.com/api/avataaars/27744.svg?size=150",
                max_length=250,
                verbose_name="Profile Image URL",
            ),
        ),
    ]
