# Generated by Django 3.1.14 on 2022-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20220124_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(default='https://avatars.dicebear.com/api/avataaars/63908.svg?size=150', max_length=250, verbose_name='Profile Image URL'),
        ),
    ]
