# Generated by Django 3.1.14 on 2022-02-14 22:39

from django.db import migrations, models
import django.db.models.deletion
import nonovium_video_backend.video_encoder.fields
import nonovium_video_backend.video_encoder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('field_name', models.CharField(max_length=255)),
                ('progress', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Progress')),
                ('format', models.CharField(editable=False, max_length=255, verbose_name='Format')),
                ('file', nonovium_video_backend.video_encoder.fields.VideoField(editable=False, height_field='height', max_length=2048, upload_to=nonovium_video_backend.video_encoder.models.upload_format_to, verbose_name='File', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(editable=False, null=True, verbose_name='Height')),
                ('duration', models.PositiveIntegerField(editable=False, null=True, verbose_name='Duration (s)')),
                ('size', models.PositiveIntegerField(editable=False, null=True, verbose_name='File Size (bytes)')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
    ]
