# Generated by Django 3.1.13 on 2022-01-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nonovium_video_backend.pipelines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('file', models.FileField(upload_to=nonovium_video_backend.pipelines.models.user_directory_path)),
                ('video_id', models.UUIDField(default='$7b2a4f90-47be-411a-b5c7-b8c395efdc2f', primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
