# Generated by Django 3.1.14 on 2022-02-14 22:39

from django.db import migrations, models
import nonovium_video_backend.pipelines.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=nonovium_video_backend.pipelines.models.user_directory_path)),
                ('video_id', models.CharField(default=nonovium_video_backend.pipelines.models.short_video_id, editable=False, max_length=12)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('size', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('media_info', models.TextField(blank=True, editable=False, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=nonovium_video_backend.pipelines.models.user_directory_path)),
            ],
        ),
    ]
