# Generated by Django 3.1.14 on 2022-01-23 23:54

from django.db import migrations, models
import nonovium_video_backend.pipelines.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=nonovium_video_backend.pipelines.models.user_directory_path),
        ),
    ]
