# Generated by Django 3.1.13 on 2022-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video_id',
            field=models.UUIDField(default='$fdc6d087-7243-4107-be33-ec1e3454805a', primary_key=True, serialize=False),
        ),
    ]
