# Generated by Django 3.1.14 on 2022-01-24 11:56

from django.db import migrations, models
import nonovium_video_backend.pipelines.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0003_auto_20220124_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video_id',
            field=models.CharField(default=nonovium_video_backend.pipelines.models.short_video_id, editable=False, max_length=12),
        ),
    ]
