# Generated by Django 3.1.14 on 2022-01-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_auto_20220124_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='width',
        ),
    ]
