# Generated by Django 3.1.14 on 2022-01-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_auto_20220124_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='size',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
