# Generated by Django 3.1.14 on 2022-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0006_auto_20220124_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='media_info',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
