# Generated by Django 3.1.14 on 2022-01-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_videofile_media_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
