# Generated by Django 3.1.14 on 2022-02-14 22:39

from django.db import migrations, models
import nonovium_video_backend.gears.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearFile',
            fields=[
                ('file', models.FileField(upload_to=nonovium_video_backend.gears.models.user_directory_path)),
                ('gear_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
