# Generated by Django 3.1.13 on 2022-01-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nonovium_video_backend.gears.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GearFile',
            fields=[
                ('file', models.FileField(upload_to=nonovium_video_backend.gears.models.user_directory_path)),
                ('gear_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
